# This file was generated by GoReleaser. DO NOT EDIT.
class Shonenjump < Formula
  desc "A faster way to change directory and improve command line productivity."
  homepage "https://github.com/suzaku/shonenjump"
  version "0.7.20"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/suzaku/shonenjump/releases/download/v0.7.20/shonenjump_Mac_x86_64.tar.gz"
    sha256 "8783dabda58d630a6701f8fb008d2d37fdf688b7aa5a580feeff17bd866ea181"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/suzaku/shonenjump/releases/download/v0.7.20/shonenjump_Linux_x86_64.tar.gz"
    sha256 "e28016a0971bc5ad81ffc94befa45b90fd21f83bb6fd3f17f8efed9a8af9638c"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/suzaku/shonenjump/releases/download/v0.7.20/shonenjump_Linux_armv6.tar.gz"
    sha256 "d247850ec2821f4a785e2082f40852c64638054c15a6115108939d79dc460df7"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/suzaku/shonenjump/releases/download/v0.7.20/shonenjump_Linux_arm64.tar.gz"
    sha256 "a797969aef2816efc1d6eeb9f30070a7514e39ba25767d8b7db56b571e49cda3"
  end

  def install
    bin.install "shonenjump"
    path = prefix/"etc/profile.d"
    path.mkpath
    system "cp", "scripts/shonenjump.bash", path/"shonenjump.bash"
    system "cp", "scripts/shonenjump.zsh", path/"shonenjump.zsh"
    system "cp", "scripts/shonenjump.fish", path/"shonenjump.fish"
    zsh_completion.install "scripts/_j" => "_j"
    fish_completion.install "scripts/j.fish"
  end

  def caveats; <<~EOS
    If you are using Bash, add the following line to your ~/.bash_profile:

      [ -f #{etc}/profile.d/shonenjump.bash ] && . #{etc}/profile.d/shonenjump.bash

    If you are using Zsh, add the following line to your ~/.zshrc:

      [ -f #{etc}/profile.d/shonenjump.zsh ] && . #{etc}/profile.d/shonenjump.zsh

    If you are using Fish, add the following line to your ~/.config/fish/config.fish:

      [ -f #{etc}/profile.d/shonenjump.fish ]; and . #{etc}/profile.d/shonenjump.fish
  EOS
  end

  test do
    system "#{bin}/shonenjump -version"
  end
end
