# This file was generated by GoReleaser. DO NOT EDIT.
class Shonenjump < Formula
  desc "A faster way to change directory and improve command line productivity."
  homepage "https://github.com/suzaku/shonenjump"
  version "0.7.19"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/suzaku/shonenjump/releases/download/v0.7.19/shonenjump_Mac_x86_64.tar.gz"
    sha256 "e47dc9ede6cd369dec15a82121ceffffe9f79fa2082417f181d95df8dc42bf97"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/suzaku/shonenjump/releases/download/v0.7.19/shonenjump_Linux_x86_64.tar.gz"
    sha256 "9d4ded67d98692aaef4b7f73610074595b0675095ca2e77cf9e2d324b3209d5e"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/suzaku/shonenjump/releases/download/v0.7.19/shonenjump_Linux_armv6.tar.gz"
    sha256 "802fac607efc25661cff78008e34bdfcf918bcfd7d999301d84081279ee6eb2f"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/suzaku/shonenjump/releases/download/v0.7.19/shonenjump_Linux_arm64.tar.gz"
    sha256 "3a2ff2e9e36eea0aeb3a2822325d998add87fa46e18c7b02a897c97a64642449"
  end

  def install
    bin.install "shonenjump"
    path = prefix/"etc/profile.d"
    path.mkpath
    system "cp", "scripts/shonenjump.bash", path/"shonenjump.bash"
    system "cp", "scripts/shonenjump.zsh", path/"shonenjump.zsh"
    system "cp", "scripts/shonenjump.fish", path/"shonenjump.fish"
    zsh_completion.install "scripts/_j" => "_j"
    fish_completion.install "scripts/j.fish"
  end

  def caveats; <<~EOS
    If you are using Bash, add the following line to your ~/.bash_profile:

      [ -f #{etc}/profile.d/shonenjump.bash ] && . #{etc}/profile.d/shonenjump.bash

    If you are using Zsh, add the following line to your ~/.zshrc:

      [ -f #{etc}/profile.d/shonenjump.zsh ] && . #{etc}/profile.d/shonenjump.zsh

    If you are using Fish, add the following line to your ~/.config/fish/config.fish:

      [ -f #{etc}/profile.d/shonenjump.fish ]; and . #{etc}/profile.d/shonenjump.fish
  EOS
  end

  test do
    system "#{bin}/shonenjump -version"
  end
end
